name: first_flutter_project
description: 'A bilingual Flutter shopping application.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_quick_nav: ^1.0.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/local_product.jpg

  fonts:
    - family: Suwannaphum-Regular
      fonts:
        - asset: assets/fonts/Suwannaphum-Regular.ttf
